services:
  portfolio:
    build: .
    image: badbl0cks/portfolio
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      proxynet:
        aliases:
          - portfolio-${RELEASE_TYPE}
    healthcheck:
      test: ["CMD", "curl", "-f", "-s", "--max-time", "5", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 120s
